import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { SessionProvider } from 'next-auth/react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html>
        <Head>
            <title>Nextjs Course</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <body>
          <div className={`min-h-screen bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-white ${geistSans.variable} antialiased`}>
              <header className="w-full bg-white dark:bg-gray-800 shadow-md p-4 sticky top-0">
                  <div className="container mx-auto flex justify-between items-center">
                      <h1 className="text-xl font-bold">
                          ShareLink
                      </h1>
                  </div>
              </header>
              <main className="container mx-auto p-4">
                  { children }
              </main>
          </div>
        </body>
      </html>
    </>
  );
}
